const assert = require("node:assert/strict");
const test = require("node:test");
const { mergeManagedSshConfig } = require("../out/sshConfig");

const generated = `# Generated by agentkernel ssh-config

Host agentkernel-dev
    HostName localhost
    Port 52341
    User sandbox
    ProxyCommand agentkernel ssh-proxy dev`;

test("merges a managed host block while preserving user config", () => {
  const first = mergeManagedSshConfig(
    "Host work\n    HostName git.example.com\n",
    "dev",
    generated,
  );
  assert.match(first, /Host work/);
  assert.match(first, /# >>> agentkernel-vscode dev/);
  assert.match(first, /Host agentkernel-dev/);

  const second = mergeManagedSshConfig(first, "dev", generated.replace("52341", "52342"));
  assert.equal((second.match(/Host agentkernel-dev/g) || []).length, 1);
  assert.match(second, /Port 52342/);
  assert.match(second, /Host work/);
});

test("keeps separately managed sandboxes independent", () => {
  const dev = mergeManagedSshConfig("", "dev", generated);
  const testConfig = generated.replaceAll("dev", "test").replace("52341", "52343");
  const both = mergeManagedSshConfig(dev, "test", testConfig);
  assert.match(both, /Host agentkernel-dev/);
  assert.match(both, /Host agentkernel-test/);
});
